name: Scala CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - uses: coursier/cache-action@v6
        id: coursier-cache

      - name: Check Formatting
        run: ./mill Alias/run checkfmt

      - name: Run tests for all projects
        run: ./mill Alias/run testall

    # - name: Run code coverage
    #   run: ./mill coverage

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v3
